### ISSUE TITLE
Add /maintenanceStatus

### ISSUE THREAD

**Issue by adityabaravkar** [infinite-options/myspace-backend#45]
- [x] HTTP methods: GET
- [x] Get all maintenance requests & related quotes, grouped by latest statuses and sorted by opened longest.
- [x] Local test through postman
- [x] Create a new branch, commit changes, and raise PR 
- [ ] Live endpoint test after deployment

**Comment by gthampi** [comment]
Need to confirm fields needed on the UI

**Comment by gthampi** [comment]
figma screen for 'tenant' didn't have the appropriate statuses and corresponding colors (as compared to the statuses table in the figma). I've used the values from the Owner flow since the Tenant has mostly same statuses.
